# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3915bce7e7a107dd1043fa8dc8fb786bc129a8baa9b0b12496de6b16c6d7c67bca3ec6a38644b9fd5c6577b45dabfaa1b6d175dbda2ccce632814bd70b4ca354

test:
  secret_key_base: 64fc6417958a6d254683dcff006146be36483ae745170dc2bbc0df3786be784b34e00bdb394ec957116be808230ef0bc4d275af9bc8983c93c2173518e52fe74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
