# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3ad424b27a74b90715ab9a650ab8ddd848ede0f88ab50de438ece5661f39a606c8b3f5ec2e6e3f9a0c480b6dba8eea70af1c67bbb85458de7f382485ec4cf32

test:
  secret_key_base: 2e86dd2d2549b970d4278612643465da6966835505efd0c03bbd33493cb0013b849695f94b46ada219b59498839f3e133a5616db0d5b34b5d435a6d66f539aa2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
